Add bookings
mvinogradovHub/java-shareit pull request #2
Opened 2023-05-19 16:42 UTC by mvinogradovHub

2023-05-20 11:17 UTC, TomattmanYandex requested changes
Привет, хорошая работа. 
Коменты как обычно в коде, многие я не дублировал.
Так же стоило бы поработать нед небольшим рефакторингом, самое простое это где можно упростить имена переменных, сделать запросы по именам методов, и т.д.

2023-05-20 11:17 UTC, TomattmanYandex commented on pom.xml
> +		<dependency>
зачем эта библиотека, обычно хватает spring jpa

2023-05-20 11:17 UTC, TomattmanYandex commented on pom.xml
> +			<plugin>
и плагин этот зачем?

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto addBooking(@Valid @RequestBody BookingWithoutAttachObjDto bookingWithoutAttachObjDto, @RequestHeader("X-Sharer-User-Id") Long userId) {
коментарий так, по визуальной части
если у нас есть в параметре только одна bokingDto то зачем имя переменной писать таким длинным, ведь хватит и просто bookingDto

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking) {
почему бы не обозвать метод itemToDto
а второй - dtoToItem по имени класса будет понятно что маппим, а так в мапперах могут быть методы с одинаковыми именами?

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
в классе часть запросов можно переделать в таком же стиле как первый метод, оно воспринимается полегче

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public BookingDto addBooking(BookingWithoutAttachObjDto bookingWithoutAttachObjDto, Long userId) {
и вот тут снова, обозвать переменную bookingDto и метод сразу станет в разы менее массивным и легче читаемым

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new NotFoundException("Booking with ID " + bookingId + " not found"));
второй вариант сделать в репозитории метод findByidAndOwnerId

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public void checkItemOwnerOrAfter(Booking booking, Long userId) {
Это воспринимается не совсем валидацией, это больше проверка безопасности , поэтому может быть лучше сделать было просто в сервисе отдельным методом

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingWithoutAttachObjDto.java
> +public class BookingWithoutAttachObjDto {
а зачем вторая Dto если можно юзать первую но просто ненужные поля будут null

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/BadStatusException.java
> +public class BadStatusException extends RuntimeException {
Так много разных ошибок, может лучше было бы их как ни будь сгруппировать, а углубленно проблему пердавать в сообщении об ошибке

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/BadStatusException.java
> +public class BadStatusException extends RuntimeException {
самый простой пример, UserMailAlreadyExist это по сути то же самое что и ErrorToCreate но с большими деталями

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +package ru.practicum.shareit.item;
раз так много классов о коменте, может стоило сделать под него отдельный пакет, или подпакет в этом пакете

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> getCommentsItem(Long itemId);
снова кажется что тут хватило бы запроса построенного по имени метода 
findByItemIdOrderByCreatedDesc

2023-05-20 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    Long id;
Если что то добавляешь, то добавляй сразу правильно, с модификатором доступа)))

2023-05-21 17:38 UTC, mvinogradovHub commented on pom.xml
> +		<dependency>
Не добавлял, был в шаблоне изначально. Убрал

2023-05-21 17:38 UTC, mvinogradovHub commented on pom.xml
> +			<plugin>
Не добавлял, был в шаблоне изначально. Убрал

2023-05-21 17:41 UTC, mvinogradovHub commented on pom.xml
> +			<plugin>
Я пытался настроить QueryDSL, но не вышло

2023-05-21 18:13 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto addBooking(@Valid @RequestBody BookingWithoutAttachObjDto bookingWithoutAttachObjDto, @RequestHeader("X-Sharer-User-Id") Long userId) {
В параметре то одна dto, но у меня для booking 2 dto
1. BookingDto - используется для возвращаемых объектов в контроллере BookingController. Содержит вложенные объекты. Если итем и брокер передать как id, то тесты не пройдут
2. BookingWithoutAttachObjDto - используется для входящих объектов. Не содержит вложенные объекты. В тестах например итем передается как itemId. Также используется как вложенные объект в item

Я не понял как эту разную логику сделать одним bookingDto. Поясните пожалуйста

2023-05-21 19:09 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking) {
поправил

2023-05-21 19:09 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto addBooking(@Valid @RequestBody BookingWithoutAttachObjDto bookingWithoutAttachObjDto, @RequestHeader("X-Sharer-User-Id") Long userId) {
Может это относилось к ItemDto? Там я исправил

2023-05-21 19:13 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingWithoutAttachObjDto.java
> +public class BookingWithoutAttachObjDto {
писал выше, что отличия чуть больше

2023-05-21 19:43 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
Переделал часть. Но честно говоря мне эти длинные названия методов не нравятся. Имхо читаемость хуже

2023-05-21 19:44 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +package ru.practicum.shareit.item;
Я бы так и сделал, но в задании четко сказано, цитата : "Поскольку отзыв — вспомогательная сущность и по сути часть вещи, отдельный пакет для отзывов не нужен. Поместите класс в пакет item"

2023-05-21 19:46 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> getCommentsItem(Long itemId);
Так не работает, я пробовал т.к. у меня item вложенный объект comment.item.id

2023-05-21 20:00 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/exception/BadStatusException.java
> +public class BadStatusException extends RuntimeException {
поправил

2023-05-22 12:57 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto addBooking(@Valid @RequestBody BookingWithoutAttachObjDto bookingWithoutAttachObjDto, @RequestHeader("X-Sharer-User-Id") Long userId) {
хмм, у меня обычно на проектах itemID передается не как просто переменная, а как обьект item у которого есть поле  Id тогда все ок
Но вообще коментарий тут был про то, что тип переменной может быть BookingWithoutAttachObjDto но имя переменной можно было бы сделать booking или bookingDto чтобы читалось гораздо легче, ибо эти дополнительные буквы в имени переменной не несут много смысловой нагрузки но приходится их читать и как то обрабатывать

2023-05-22 12:59 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> getCommentsItem(Long itemId);
А разве Jpa не позволяет строить запрос с такой вложенностью? просто имя каждой внутренней переменной начинаешь с большой буквы и все

2023-05-22 13:01 UTC, TomattmanYandex approved these changes
Принято, но к следующему спринту глянь моменты которые были в коментах

2023-05-22 14:49 UTC, merged

2023-05-31 13:00 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public void checkItemOwnerOrAfter(Booking booking, Long userId) {
Тогда придется дублировать код т.к. у меня эта проверка в двух классах

2023-05-31 13:05 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> getCommentsItem(Long itemId);
Исправил. Не знаю почему не получилось в первый раз )