add-item-request
mvinogradovHub/java-shareit pull request #3
Opened 2023-06-06 14:55 UTC by mvinogradovHub

2023-06-07 13:08 UTC, TomattmanYandex requested changes
Привет, по поводу т.з. вроде как все хорошо, кроме того что тесты сервисов должны быть как юнит с моками, так и интеграционные, также 
 (Реализовать тесты для работы с JSON для DTO в вашем приложении с помощью аннотации @JsonTest. Такие тесты имеют смысл в тех случаях, когда ваши DTO содержат в себе некоторую логику. Например, описание формата дат или валидацию. Выберите DTO, где есть подобные условия, и напишите тесты.)

А теперь самая большая боль

форматирование в коде надо переделать, читать и понимать нереально,
Размеры табов то 2 то 4 
структура лесенкой - тяжела, код надо писать не чтобы смотрелся красиво, а чтобы читался понятно (а лучше и то и другое, но в первую очередь понятность)

Я пройдусь еще раз сейчас по проекту, оставлю по одному комментарию, на большинство проблем форматирования, но поправить надо будет везде

Сделал на пример букинга, остальные по тем же коментам

Без нормального форматирования не пропущу

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Pageable page = convertToPageSettings(start, size, "start");
Что за параметр start, что он обозначает?

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    if (itemRequestId != null) {
Извиняюсь кончено, но эту конструкцию невозможно прочитать
каждая строка - новая вложенность, не понять почему
Да и вообще вложенность на вложенности и вложенностью погоняет
Почему бы не сделать отдельную переменную куда закинуть полученый итемРеквест из репозитория,
почему бы не сделать так
1) проверить пользователя
2) сделать из ItemDto обьект
3) if (itemRequestId != null) {
3.1) получить в перменную реквест
3.2) записать ее в обьект из пункта 2
3.3) конец блока if
4) сохранить в базу и вернуть полученный результат

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +      return ItemMapper.itemToItemDto(
и снова что-то не читаемое
почему бы в маппере не перегрузить метод 
itemToItemDto сделать новый который будет принимать только один параметр
а внутри он уже будет вызывать этот метод но с остальными параметрами равными null как минимум читаться станет легче
А с текущим стилем, я в начале не мог понять почему у метода save 4 параметра, потом почему у маппера 4 параметра (кстати это тоже лучше исправить, это похоже больше на логику сервиса) проставление дополнительных полей

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    userRepository
снова перенос какой то не в тему
userRepository.findById(userId) //обьект с которым работаем
                        .orElseThrow(() -> new NotFoundException("User with ID " + userId + " not found")); //дополнительные действия с ним

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item item =
снова структура лесенкой не надо так

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    return ItemMapper.itemToItemDto(
вот тут так как мы никак поля из lastBookingWithoutObjDto и nextBookingWithoutObjDto не мапим а просто проставляем, лучше делать проставлять эти объекты в itemDto в самом сервисе

2023-06-07 13:08 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +class BookingRepositoryTest {
тест должен быть в отдельной базе, а не соновной

2023-06-07 13:08 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +class BookingServiceTest {
тесты сервиса должны быть частично юнит, частично интеграционные, т.е. с реальными репозиториями

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +      @RequestHeader("X-Sharer-User-Id") Long userId, @PathVariable Long bookingId) {
тут точно надо было переносить на новую строку?
если начал переносить, то лучше или каждую переменную в новую строчку, или все в одну, либо переносить уже то что не влазит
а то сейчас по аналогии с предыдущими методами, кажется что только один параметр, а их два

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    log.info(
чаще первый параметр оставляют в строке, а все остальные уже переносят, и тоже два варианта, либо каждый параметр потом с новой строки, или можно слегка сгруппировать например в логах первый параметр само сообщение, остаивть его в строке с командой, а остальные - параметры для плейсхолдера, их все закинуть в новую строку

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +  public static Booking bookingDtoToBooking(BookingWithoutObjDto bookingDto, User user, Item item) {
изера и итем, лучше проставлять в сервисе а не в маппере, паре преобразует поля одного объекта к полям другого, в случае с юзером и айтемом это не маппинг, это логика сервиса

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +      Long bookerId, LocalDateTime localDateTime, LocalDateTime localDateTime2, Pageable pageable);
перенос всех переменных на новую строку тяжело читать, лучше если переносить первый параметр тоже, то переносить каждый в новую строку, 
попробуй сделать все в одну строку и посмотри как его перенесет автоформатирование, это второй вараинт, текущий вариант непонятен

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +          + " (b.status = 'REJECTED' OR b.status = 'CANCELED')")
стоитло ли переносить эту строку, это часть Where следовательно стоило оставить с ним в одной строке, либо переносить каждое условие, либо добваить уровень вложенности

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        userRepository
зачем этот перенос

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            .findById(userId)
про этот перенос я уже где то писал

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        itemRepository
все аналогично

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        .findById(userId)
про это тоже

2023-06-07 13:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            bookingRepository.findByItemOwnerId(userId, page));
снова, что аз переносы

2023-06-08 10:49 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Pageable page = convertToPageSettings(start, size, "start");
исправил на from, как в контроллере. Это начальная запись с который показывать выборку

2023-06-08 10:49 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    if (itemRequestId != null) {
fix

2023-06-08 11:21 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +      return ItemMapper.itemToItemDto(
fix

2023-06-08 11:21 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    userRepository
fix

2023-06-08 11:22 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item item =
fix

2023-06-08 11:22 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        userRepository
fix

2023-06-08 11:22 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            .findById(userId)
fix

2023-06-08 11:22 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        itemRepository
fix

2023-06-08 11:23 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            bookingRepository.findByItemOwnerId(userId, page));
fix

2023-06-09 08:05 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Pageable page = convertToPageSettings(start, size, "start");
вопрос был про третий параметр, который прям передается как строка "start"

2023-06-09 08:13 UTC, TomattmanYandex requested changes
Привет, пара моментов остались без ответа, плюс интеграционные тесты немного надо переделать

2023-06-09 08:13 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +class BookingRepositoryTest {
Коммент без ответа

2023-06-09 08:13 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
интеграционные тесты должны быть не в основной базе

2023-06-09 08:13 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    void addBookings() {
по поводу интеграционных тестов, имеет смысл переделать тесты так, что вызываешь метод save на уровне сервиса, а получаешь обьект для проверки с уровня базы, потому что есть вероятность того, что метод ничего не делает, а просто возвращает объект, и тогда у нас есть тест который будет возвращать результат что все работает правильно ,при не рабочем коде

2023-06-09 08:13 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    void addBooking_whenAddBooking_thenStatusWaiting() {
вверху комент я оставлял про этот тест

2023-06-09 09:58 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Pageable page = convertToPageSettings(start, size, "start");
Сюда передается название поля по которому происходит сортировка. Поменял название параметра на более понятное

2023-06-09 09:59 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        .findById(userId)
лесенки я сразу исправил, просто забыл отписать по этому комменту

2023-06-09 10:15 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    return ItemMapper.itemToItemDto(
гитхаб скрыл часть комментов под кнопкой, а я не заметил сразу. Исправляюсь.
Что касается замечания, то, если я правильно понял, я не могу проставить эти поля в сервисе, так как Item у меня не содержит этих полей.

2023-06-09 10:16 UTC, mvinogradovHub commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +class BookingServiceTest {
это я сделал как BookingServiceIntegrationTest

2023-06-09 10:27 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +      @RequestHeader("X-Sharer-User-Id") Long userId, @PathVariable Long bookingId) {
это я поправил в прошлый раз

2023-06-09 10:28 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    log.info(
аналогично, плагин от гугла все испортил. Исправлено

2023-06-09 10:30 UTC, mvinogradovHub commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +class BookingRepositoryTest {
Сделал

2023-06-09 10:55 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +  public static Booking bookingDtoToBooking(BookingWithoutObjDto bookingDto, User user, Item item) {
исправил

2023-06-09 10:55 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +      Long bookerId, LocalDateTime localDateTime, LocalDateTime localDateTime2, Pageable pageable);
готово

2023-06-09 10:56 UTC, mvinogradovHub commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +          + " (b.status = 'REJECTED' OR b.status = 'CANCELED')")
fix

2023-06-09 11:00 UTC, mvinogradovHub commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
сделал

2023-06-09 12:29 UTC, mvinogradovHub commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    void addBooking_whenAddBooking_thenStatusWaiting() {
исправил для этого теста

2023-06-09 12:29 UTC, mvinogradovHub commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    void addBookings() {
сделал для addBooking_whenAddBooking_thenStatusWaiting()

2023-06-10 09:07 UTC, TomattmanYandex approved these changes
Принято

2023-06-29 07:16 UTC, merged